name: add-epic-to-project
description: This action takes issues with a certain tag and add the title as a new option in a projects custom field single select field.
author: Jens Plüddemann <jens.plueddmann@novatec-gmbh.de>
inputs:
  project-url:
    required: true
    description: URL of the project to add issues to
  github-token:
    required: true
    description: A GitHub personal access token with write access to the project
  labels:
    required: false
    default: epic
    description: A comma-separated list of labels to use as a filter for issue to be added
  label-operator:
    required: false
    default: or
    description: The behavior of the labels filter, AND to match all labels, OR to match any label, NOT to exclude any listed label (default is OR)
runs:
  using: "docker"
  image: "docker://ghcr.io/jensereal/add-epic-to-project:v1"
  args:
    - ${{ inputs.project-url }}
    - ${{ inputs.github-token }}
    - ${{ inputs.labels }}
    - ${{ inputs.label-operator }}
